### ISSUE TITLE
Different route and container names

### ISSUE THREAD

**Issue by SteveEdson** [umbraco-community/UmbracoFileSystemProviders.Azure#110]
Hi,

Please could you explain how we can use a different route name to the container name? We have been able to use a route of `/media`, pointing to a different container name, but we can't figure out how to have a route of `/example`, pointing to a container called `media`.

Any help would be appreciated, thanks.

**Comment by michael-nee** [comment]
I have the same issue as well.

**Comment by JimBobSquarePants** [comment]
You can't configure that behaviour with the default provider why would you expect it to be possible with this one?

**Comment by michael-nee** [comment]
I've got this working now.  Had to change some extra settings in web.config.
