### ISSUE TITLE
Images stopped working

### ISSUE THREAD

**Issue by villian** [umbraco-community/UmbracoFileSystemProviders.Azure#113]
Images just stopped working on our site, the time on the server is the same as Azure portal.

We are not able to upload images to the media section and view them via Umbraco Media section.

Interesting that we can see the image if we are using ImageProcessor, so something with authentication to azure, tried to regenerate access key - didn't help.

**Comment by idseefeld** [comment]
@villian Please provide more details. All related configuration, Umbraco version etc. - leave out security key of course;-)
But first check all documentation carefully.
If the Azure credentials work for ImageProcessor, I guess something with your entire setup is wrong.

Yours Dirk

**Comment by JimBobSquarePants** [comment]
Check the examine indexes also. They've been responsible in the past.
