### ISSUE TITLE
Unwanted change of link to media

### ISSUE THREAD

**Issue by CasperTDK** [umbraco-community/UmbracoFileSystemProviders.Azure#120]
"We are having problems with changing media links when replacing (re-uploading) an existing media file. Our marketeers use this URL in several HTML pages and other communication. They are used to only replacing the image, with the URL staying intact.

Each uploads seems to create a new folder on the storage location (AzureFileSystemProvider/blob storage) and deleting the old one. "

See:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/89715-unwanted-change-of-link-to-media

"I was able to reproduce this with

Blank web project in Visual Studio
Install Umbraco 7.8.1 with NuGet, database SqlCE (now replacing images works fine, folder ID is kept as it initially was)
Install UmbracoFileSystemProviders.Azure 1.0.2 with NuGet and use configuration as installed with package (of course change configuration to use your own Azure blob storage) (now replacing images works incorrect, new folder ID gets generated with each replacement, old image on blob storage gets deleted)"

It works as intended for 
"Umbraco.Core.IO.PhysicalFileSystem, Umbraco.Core".

Can we change the behaviour to match PhysicalFilesystem?

**Comment by JimBobSquarePants** [comment]
Hi @CasperTDK 

There's actually already a PR open to fix this. 

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/pull/106

We can't merge it though until we know the exact version Umbraco changed the behaviour which broke our provider. If you can figure this out that would be awesome.

Cheers

James

**Comment by CasperTDK** [comment]
@JimBobSquarePants  Ah, sorry. I searched in existing issues, but I did not discover this ticket.

One observation: it works in Umbraco.Core.IO.PhysicalFileSystem in any version - so shouldn't we be able to use the same path-local regardless of umbraco version?

if I set up an umbraco site in azure with version 7.5.14 - and confirms that updating media items does not affect links - we can make a new release. Correct? 
if so, I will do that today

**Comment by CasperTDK** [comment]
@JimBobSquarePants  I've just tested it with Umbraco 7.5.13 using UmbracoFileSystemProviders.Azure -Version 1.0.2

I created a new folder in umbraco. I uploaded a folder called moon.jpg:
media/1001/moon.jpg

This results in media/1001/moon.jpg is created in azure blob storage

I then overwrote the file with leverance.jpg.

This deleted media/1001/moon.jpg on azure and leverance was now created as:
media/1001/leverance-model.jpg

I then removed the file in umbraco and then choosed moon.jpg.
This created media/1001/moon.jpg and removed media/1001/leverance-model.jpg in azure.

So everything is worked as intended on Umbraco 7.5.13

On newer versions of umbraco, it does not work as intended.

**Comment by CasperTDK** [comment]
@JimBobSquarePants  Let me know if you need more testing. Our authors can not link directly to media right now, in fear of the changing links. They often need to link to pds - which does get updated

**Comment by ShomronMalamTeam** [comment]
Hello,

we are using Umbraco 7.7.8, and that issue is still happening, is there a quick fix for that ?

Thanks.

**Comment by ShomronMalamTeam** [comment]
Hello People

I'm using umbraco 7.7.8, and that issue is still happening, is there a quick fix for that issue ? 

it really urgent.

Thanks.
