### ISSUE TITLE
Naming settings problem in Azure Key Vault

### ISSUE THREAD

**Issue by sonphnt** [umbraco-community/UmbracoFileSystemProviders.Azure#125]
Hi,

I am applying Azure Key Vault to hide all sensitive in settings. Azure Key Vault is not supporting "dot" in Name. Can we change/improve by removing "dot" in Name setting in webconfig file.

Ex:
`<add key="AzureBlobFileSystem.ConnectionString:media" value="XXXXX" />`

Thanks

**Comment by Jeavon** [comment]
A shortcoming of Key Vault - https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/33931111-secret-names-do-not-support-special-characters I'm not totally clear if it supports the colons either but some suggestion that hyphen is supported...
