### ISSUE TITLE
Setting Key AzureCDNToolkit:UseAzureCdnToolkit" to false - what is expected behaviour?

### ISSUE THREAD

**Issue by quinlandm** [umbraco-community/UmbracoFileSystemProviders.Azure#133]
Hi all, 
When AzureCDNToolkit:UseAzureCdnToolkit is set to false, I would expect all images and assets to be served from local folders, i.e. as in how the site worked prior to installation / configuration of this plugin.

Prior to setting up this plugin... paths in markup to assets such as js/css were

`src="/assets/js/all.min.js"`

to make all work with the ToolKit, the markup had to be update to..

`src="@Url.ResolveCdn("/js/all.min.js")"`

The result of setting the flag above to false now means that no css/assets basically anything modified to use Url.ResolveCdn() had to have "assets" removed from the path, as this seems to include "assets" when referencing the containers in blob storage.

Images from Media are loading as expected from local Media folders.

Is this a bug, or is there some other configuration I need to have in place?  Or do I need to write something to cater for this myself (or move the js/css files)?

Thanks,

David

**Comment by Jeavon** [comment]
This was posted to the wrong repo I think?
