### ISSUE TITLE
Logs file?

### ISSUE THREAD

**Issue by yaplex** [umbraco-community/UmbracoFileSystemProviders.Azure#148]
I am trying to configure this plugin for Umbraco 8.2.0 but nothing happens after installing it. Is it a log file or something which I can look into to understand what is wrong with my configuration?

What I did:
1. Installed alpha version of plugin using Nuget
2. added configuraiton (appConfig) as indicated there: https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/tree/develop-umbraco-version-8#configuration-via-webconfig
3. Updated security file for Image processor as indicated there: https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/tree/develop-umbraco-version-8#combining-with-imageprocessor

Thanks,
Alex
https://yaplex.com

**Comment by stevetemple** [comment]
Did you install just the core? Are you planning on using it for media, forms or both?

**Comment by yaplex** [comment]
Do you mean Umbraco Core? No, I installed the whole CMS.
I need it just for the media.

**Comment by yaplex** [comment]
Also, is it possible to install it using the Umbraco package manager? as I understand in that case it will do most of the configuration itself. But when choosing that package I can see only version 1.x, there is no way to select 2.x alpha.

**Comment by yaplex** [comment]
I was installing a Nuget package, but I have to install the Umbraco package. It was my mistake. Everything works fine.

**Comment by stevetemple** [comment]
OK thanks for letting us know @yaplex
