### ISSUE TITLE
Umbraco cloud

### ISSUE THREAD

**Issue by efabioli** [umbraco-community/UmbracoFileSystemProviders.Azure#151]
Hi all,

I am getting this error when I try to restore content after installation of 2.0.0-alpha 4 package into my umbraco cloud project.

> EXCEPTION:
> 
> System.AggregateException: Failed to apply all changes (see exceptions).
>    at Umbraco.Core.IO.ShadowFileSystem.Complete()
>    at Umbraco.Core.IO.ShadowWrapper.UnShadow(Boolean complete)
>    at Umbraco.Core.IO.FileSystems.EndShadow(String id, Boolean completed)
> 
> AGGREGATE:
>   System.Exception: Could not save file "oiuf4eva/desktop-notebook-glasses.jpg".

 
 

 
Any suggestions?

Thanks,
Emiliano

**Comment by efabioli** [comment]
Hope this can help:

I have cloned the repo and set [this property](https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/blob/e31679a51e9bc2e4183cb4fecc82dc7fad27093e/src/UmbracoFileSystemProviders.Azure/AzureBlobFileSystem.cs#L162) to be false by default in order to skip this [check here](https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.5/src/Umbraco.Core/IO/ShadowFileSystem.cs#L34) and all work.

**Comment by stevetemple** [comment]
Hi @efabioli 

That looks like a sensible fix, as it can't ever add a physical file. I'll look into sorting an update out

Cheers,

Steve
