### ISSUE TITLE
Forms does not work with Umbraco.Forms v8.3.0

### ISSUE THREAD

**Issue by samgooch** [umbraco-community/UmbracoFileSystemProviders.Azure#157]
Using the forms blob storage provider, I am experiencing an odd issue. Creating a test form will insert the form but also insert a load of workflows within the section.

![image](https://user-images.githubusercontent.com/3908022/73652390-c13c4e80-467e-11ea-84a2-0bd8df4600ab.png)

Browsing to the form will then throw an error that it can't find it.

Here is a screenshot of my container:
![image](https://user-images.githubusercontent.com/3908022/73652450-e5982b00-467e-11ea-9250-11667dfa2a81.png)

Versions installed:
- Umbraco.Cms v8.5.3
- Umbraco.Forms v8.3.0
- UmbracoFileSystemProviders.Azure.Forms v2.0.0-alpha5

**Comment by Jeavon** [comment]
@samgooch rename your container "forms-data", it cannot be named "forms". I've added a warning to this readme as it was only present on the Our docs https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/IFileSystem/#storing-the-json-files-using-the-community-umbraco-azure-blob-provider

**Comment by samgooch** [comment]
Thanks @Jeavon - that worked. And thanks for updating the README.md
