### ISSUE TITLE
image requests return 404 when no querystring is used since version 2.0.0-alpha3 and up

### ISSUE THREAD

**Issue by Swimburger** [umbraco-community/UmbracoFileSystemProviders.Azure#160]
I upgraded to the most recent version of this package (2.0.0) from 2.0.0-alpha2 and the image request started returning 404's when not using querystring parameters.
I subsequently downgraded one at a time (beta's and alpha's) back to version 2.0.0-alpha2 until it worked again.
I'm running Umbraco version 8.5.4.

Web.config
```
  <location path="media">
    <system.webServer>
      <handlers>
        <remove name="StaticFileHandler" />
        <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
      </handlers>
    </system.webServer>
  </location>
```

Media/Web.config
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <clear/>
      <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler"/>
      <add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either"
        requireAccess="Read"/>
    </handlers>
  </system.webServer>
</configuration>
```

I've downgraded back to a working version, so there's no urgency for me to resolve the issue.
Happy to help resolve this if it's an issue for other people.

**Comment by Jeavon** [comment]
@Swimburger I suspect you need to install UmbracoFileSystemProviders.Azure.Media as the package was split up for the alpha3 release - see the note here https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure#installation

**Comment by Swimburger** [comment]
You are correct. I didn't install this new package.
After updating to 2.0.0 and installing the 2.0.0 package the issue is resolved.
