### ISSUE TITLE
Not working with Umbraco v8.6.0

### ISSUE THREAD

**Issue by soelgaard** [umbraco-community/UmbracoFileSystemProviders.Azure#165]
After upgrading to version 8.6.0 the site stopped showing the images. New images are uploaded to the blob storage, but the backoffice and the frontend can't show the images.

This is what I get in the log file

{
    "@t":"2020-04-16T12:07:17.2646286Z","@mt":"Exception","@l":"Error",
    "@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: GetResponseAsync 132 : Response status code does not indicate success: 404 (The specified resource does not exist.).", 
    "SourceContext":"ImageProcessor.Web.Helpers.RemoteFile","ProcessId":40192,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"XXX","Log4NetLevel":"ERROR"
}
{
    "@t":"2020-04-16T12:07:17.2706248Z","@mt":"Exception","@l":"Error",
    "@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 609 : No image exists at https://XXX.blob.core.windows.net/media/butjvnjr/defaul_mainimage.png",
    "SourceContext":"ImageProcessor.Web.HttpModules.ImageProcessingModule","ProcessId":40192,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"XXX","Log4NetLevel":"ERROR"
}

The issues is the same when running the website as a webapp on Azure

**Comment by JimBobSquarePants** [comment]
Check the web.config in your Media folder. Has that been updated by the upgrade?

**Comment by soelgaard** [comment]
That was the problem. The web.config in media was reverted by the upgrade.
