### ISSUE TITLE
.mp4 (and .pdf) file is cut down to 4 Mb when uploaded through media section

### ISSUE THREAD

**Issue by nielslynggaard** [umbraco-community/UmbracoFileSystemProviders.Azure#166]
Hi all. 

First off, I'm not an Azure Blob experts, so if this is an issue with setup of Azure Blob storage, I hope just to be pointed in the right direction. 

Problem; Uploading a video file (.mp4) to the media library works fine. But the file is "cut", e.g a 21 Mb file is reduced to exactly 4 Mb and thus plays fine when requested but stops before the file is actually finnished. The file size in Umbraco shows the "original" file size. 

I just tested with a 20 Mb. .pdf and the is the same, it's being corrupted (I guess because it is being "cut".

I've tried;
Bumping the max file size in web.config (maxRequestLength and maxAllowedContentLength) in web.config
Bumping  the "Maxbytes" setting in imageprocessor/security.config

So far no luck. 

The Azure Blob storage isn't private and otherwise works well. 

Any help will be greatly appreciated..

**Comment by c9mbundy** [comment]
Perhaps check issue #158.

**Comment by nielslynggaard** [comment]
Thank you for pointing to that issue. I should learn to use the search :) 

Allthough the issue is closed with a release of 1.1.1, it still doesn't seem tor work for me. However, I solved it by downgrading to 1.0.3 and that seems to work.

**Comment by Jeavon** [comment]
@nielslynggaard are you sure you had the issue with 1.1.1, I did revert the change that caused the 4mb cut off for that release so I'm wondering what happened for you...

**Comment by nielslynggaard** [comment]
I am fairly sure that upgrading to 1.1.1 didn't fix the issue for me, but I will test this out again on the same project and report back
