### ISSUE TITLE
SVG files does not load

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco-community/UmbracoFileSystemProviders.Azure#167]
JPG and PNG files works fine, but SVG files do not load. 

This is in web.config 

```
<location path="media">
        <system.webServer>
            <handlers>
                <remove name="StaticFileHandler" />
                <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
            </handlers>
        </system.webServer>
    </location>
```

Contents of media/web.config are

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <clear/>
            <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler"/>
            <add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either"
                requireAccess="Read"/>
        </handlers>
    </system.webServer>
</configuration>
``` 

Umbraco 8.6.1
UmbracoFileSystemProviders.Azure 2.0.0
UmbracoFileSystemProviders.Azure.Media 2.0.0

**Comment by MichaelNielsenDK** [comment]
Sorry, I am using the Azure Blob Cache package also, that is why cached jpg and png work, while SVG did not. 

Correcting an error in the configuration solved my issue.

**Comment by skttl** [comment]
Hey @MichaelNielsenDK 

Sorry for bringing up this old issue - you don't happen to remember what error correction you did in your config, do you?

**Comment by skttl** [comment]
Nevermind, figured it out. The latest security update had reset /media/web.config, and for some reason that file was ignored in git, so I didn't notice it :)
