### ISSUE TITLE
Please upgrade to the new Key Vault client libraries

### ISSUE THREAD

**Issue by heaths** [umbraco-community/UmbracoFileSystemProviders.Azure#169]
We have released [new versions](https://aka.ms/azsdk/net) of the Azure SDK Client Libraries for Key Vault, Storage, and other Azure services. We see that you are still using the older packages. The new Azure SDK is faster, leaner, and more extensible. Please see our [introductory video](https://aka.ms/azsdk/intro) and our [value propositions](https://aka.ms/azsdk/valueprop) for more information. We hope that you upgrade to these new packages. We are happy to offer assistance in upgrading while we work on migration guides.

For Key Vault, we have split the client libraries into 3 separate packages that can be used together but, individually, are smaller dependencies:

* [Azure.Security.KeyVault.Certificates](https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/samples))
* [Azure.Security.KeyVault.Keys](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples))
* [Azure.Security.KetVault.Secrets](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples))

Samples are also available in our [samples browser](https://aka.ms/azsdk/net/keyvault/samples).

I see you [also depend on](https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/blob/d7d422d2eb53ac1ece0508978ad294a34b178838/src/UmbracoFileSystemProviders.Azure/packages.config#L30-L33) Storage, and we have several [new packages](https://www.nuget.org/packages?q=Azure.Storage) for those as well. You can use the same [Azure.Identity](https://www.nuget.org/packages/Azure.Identity/) to authenticate to both of them, using [DefaultAzureCredential](https://devblogs.microsoft.com/azure-sdk/authentication-and-the-azure-sdk/), for example, which simplifies code to work in both development and production environments.

**Comment by Jeavon** [comment]
@heaths are there any migration guides yet? Migrating our extensive usage of the Storage SDK to v12 looks to be quite a significant task

**Comment by heaths** [comment]
We have migration guides for Key Vault (MigrationGuide.md next to the README.md) I wrote after opening this issue. For storage blobs, see https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md.

**Comment by Jeavon** [comment]
v3 has now been released which is using SDK v12, thanks!
