### ISSUE TITLE
Upgrade to .Net SDK v12

### ISSUE THREAD

**Issue by Jeavon** [umbraco-community/UmbracoFileSystemProviders.Azure#175]
This looks like it's going to require significant refactoring.

A useful guide for migration - https://elcamino.cloud/articles/2020-03-30-azure-storage-blobs-net-sdk-v12-upgrade-guide-and-tips.html

**Comment by Shazwazza** [comment]
Hi all, just wondering about these 2 dependencies that are listed on the current 3 beta (https://www.nuget.org/packages/UmbracoFileSystemProviders.Azure/3.0.0-beta1):

Microsoft.Azure.KeyVault.Core (>= 3.0.3)
Microsoft.Data.Services.Client (>= 5.8.4)

The keyvault dependency https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core/ has been replaced with newer APIs too. Not sure about the `Microsoft.Data.Services.Client` one or why that one is needed. It seems that all Azure based APIs should be using `Azure.*` prefixed packages?

**Comment by Jeavon** [comment]
Thanks @Shazwazza I'll have a look at those and update or remove

**Comment by Jeavon** [comment]
@Shazwazza have removed from beta2
