### ISSUE TITLE
Is it possible to add the Media Id/Guid to the blob metadata on upload?

### ISSUE THREAD

**Issue by Shazwazza** [umbraco-community/UmbracoFileSystemProviders.Azure#176]
I haven't had a chance to peek at the code just yet but is it possible to add the Media Id/Guid to the blob metadata on upload? Else is there any sort of extension point that could be used to do this?

It would be very handy for some stuff I'm working on to be able to know which media item each blob item related to purely by looking at the blob item metadata.

Thanks!

**Comment by Shazwazza** [comment]
I suppose the answer is 'no' because the file system provider itself just adds files without being provided a context of what it's uploading. But any ideas would be most welcome :)

**Comment by Shazwazza** [comment]
Just had a look at Umbraco, turns out the file is saved before the IMedia is saved (or created) so there's no way to really figure this out. Only way would be a MediaSaved event, then lookup the associated blob and update it with the metadata.

**Comment by JimBobSquarePants** [comment]
Wouldn't doing a request be an order of magnitude slower than a db query?

In my experimental `IFileSystem` design  the media file name represents whatever the id string component of the `http://media-file/{id}` record is. That would make things predictable throughout.

https://github.com/JimBobSquarePants/Umbraco.FileSystemAbstractions/blob/71b862e1af839214c2fa8e6a2ed7b350f4d12a0d/src/Media.Core/MediaFileResolverMiddleware.cs#L64-L74

**Comment by Shazwazza** [comment]
Yes the current file system stores the file path as whatever is defined by Umbraco's `IMediaPathScheme`. These paths are predictable depending on the scheme used but the default one doesn't directly indicate the INT media id.

What I require is that the INT media id is stored as part of the blob metadata. This is a requirement for how Azure Search works for indexing file blobs in order to store the data into the same index document by it's Key which is the INT media id.

So the alternatives I have to work with today are:

* MediaService.Saved - go lookup the blob by it's path based on the IMediaPathScheme for the media file saved and update it's metadata
* Override the blob storage media file system provider methods to ensure that the INT media Id is part of the blob metadata when it's first uploaded and then replace the media file system with this custom wrapping one

**Comment by c9mbundy** [comment]
FWIW - the V7 AzureCDNToolkit uses a Keyed-Pair approach - loaded into cache. Unfortunately, it doesn't persist or maintain this pair, so has to reload it by (very) expensive lookups on every restart, and being able to lookup from metadata could be useful.

**Comment by JimBobSquarePants** [comment]
These features are all encroaching upon what a filesystem should be responsible for. 

Where would you store the metadata on the PhysicalFileSystem implementation?

**Comment by Shazwazza** [comment]
I agree, my question wasn't about if the file system abstraction itself should know about the media id, metadata, etc... purely just whether there's a way to fill in this metadata in blob storage which is why I closed the issue :)

I have a work around using MediaSaved. It's not pretty but it works (will need further error handling, etc...). It needs to use reflection because `GetBlockBlobReference` is private so I guess if that was public (I can make a PR) it would be less ugly. 

```cs
public class MyComponent : IComponent
{
    private readonly AzureBlobFileSystem _azureBlobFileSystem;
    private readonly AzureFileSystem _azureFileSystem;
    private readonly IContentSection _contentSettings;
    private readonly ILogger _logger;
    private readonly Lazy<MethodInfo> _getBlockBlobReference;

    public MyComponent(
        IMediaFileSystem mediaFileSystem,
        IContentSection contentSettings,
        ILogger logger)
    {
        _contentSettings = contentSettings;
        _logger = logger;
        _azureBlobFileSystem = mediaFileSystem.Unwrap() as AzureBlobFileSystem;
        if (_azureBlobFileSystem != null)
        {
            _azureFileSystem = _azureBlobFileSystem.FileSystem;
        }
        // private method so use reflection :( 
        _getBlockBlobReference = new Lazy<MethodInfo>(() => typeof(AzureFileSystem)
            .GetMethod("GetBlockBlobReference", BindingFlags.NonPublic | BindingFlags.Instance));
    }

    public void Initialize()
    {
        if (_azureBlobFileSystem != null)
        {
            MediaService.Saved += MediaService_Saved;
        }
    }

    public void Terminate()
    {
        MediaService.Saved -= MediaService_Saved;
    }

    private void MediaService_Saved(IMediaService sender, SaveEventArgs<IMedia> e)
    {
        var saved = e.SavedEntities.ToList();
        if (saved.Count == 0) return;

        foreach (var media in saved)
        {
            var urls = media.GetUrls(_contentSettings, _logger);
            foreach (var url in urls)
            {
                // Go get the blob and update it (reflection)
                var blob = (CloudBlockBlob)_getBlockBlobReference.Value.Invoke(_azureFileSystem, new object[] { url });
                if (blob != null && blob.Exists())
                {
                    // update the blob's metadata                     
                    blob.Metadata["mediaId"] = media.Id.ToInvariantString();
                    blob.SetMetadata();
                }
            }
        }
    }
}
```
