### ISSUE TITLE
Image cropper not working when you install UmbracoFileSystemProviders.Azure from Visual Studio. Some files and dependencies are missing

### ISSUE THREAD

**Issue by MarGraz** [umbraco-community/UmbracoFileSystemProviders.Azure#191]
The image cropper not working. **When you install the "UmbracoFileSystemProviders.Azure" via Visual Studio all the necessary dependencies and files are not included.** I had to reinstall "UmbracoFileSystemProviders.Azure" from Umbraco, via backoffice, under "Packages". 

**It seems that this problem is still here since 2016.** I opened a discussion in the [Umbraco forum](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105890-image-cropper-doesnt-work-with-azure-blob-storage-umbracofilesystemprovidersazure-v2) where **I also highlighted the missing packages and all the added files**. 

I found the solution thanks to another thread on Umbraco 7 from 2016. Please fix it!

**Comment by Jeavon** [comment]
For Umbraco v8 you need to install UmbracoFileSystemProviders.Azure.Media

**Comment by MarGraz** [comment]
> 
> 
> For Umbraco v8 you need to install UmbracoFileSystemProviders.Azure.Media

Thank you for your reply. 

I read the documentation and I think that it's difficult to understand the difference between "UmbracoFileSystemProviders.Azure" and "UmbracoFileSystemProviders.Azure.Media", because **both the packages have a "2.0.1" version**, and from the [Umbraco page](https://our.umbraco.com/packages/collaboration/umbracofilesystemprovidersazure/) the **suggested PM command indicates to install the "UmbracoFileSystemProviders.Azure" package**, and that the "v2 is for Umbraco 8.1+". It's really easy to make a mistake and install the "UmbracoFileSystemProviders.Azure".
