### ISSUE TITLE
Plans to support Umbraco v9?

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco-community/UmbracoFileSystemProviders.Azure#193]
Hi guys
Amazing package!

Question: Are there any plans to support v9?  Or with the changes in ImageProcessor, this is not the way to go?
Thanks a lot

**Comment by Jeavon** [comment]
@JoseMarcenaro Not this package, there will be an official Azure Blob provider package for v9 released by Umbraco. We will continue support for v8 with this package.

**Comment by Jeavon** [comment]
v9 repo is at https://github.com/umbraco/Umbraco.StorageProviders

**Comment by JoseMarcenaro** [comment]
Thanks @Jeavon for sharing the info!
